### PR TITLE
Add license header to .travis.yml

### PR DESCRIPTION
**Pull request by mik-laj**
Hello,

I noticed that the license header is missing in this file. I wonder if it's necessary, so I created PR to talk about it. What are your thoughts on this topic? Which files should have a header?

Best regards,

CC: @potiuk

### CODE REVIEW

**Comment by potiuk** [comment]
Yeah. Shouldn't RAT repo be checked with RAT ;) ? Eating your own dog food :D

**Comment by jochenw** [comment]
> Yeah. Shouldn't RAT repo be checked with RAT ;) ? Eating your own dog food :D

You are right, of course, Unfortunately, it's a non-trivial task, to build a Maven plugin, and use it within its own build. If you have any solutions to work around that chicken, and egg, problem: We re ready to listen.

**Comment by potiuk** [comment]
Why not using CLI interface to check it ? Surely the .jar file is built at some point in time and you can just use 'java -jar SOURCES'

**Comment by potiuk** [comment]
This way you can additionally check if the CLI interface still works.

**Comment by potiuk** [comment]
If you think it might work, I might even try to dust off my maven shelf in the brain (been there done that) and contribute it ...

**Comment by mik-laj** [comment]
I working on a PR now: https://github.com/mik-laj/creadur-rat/pull/2

**Comment by mik-laj** [comment]
Final PR: https://github.com/apache/creadur-rat/pull/15

**Comment by ottlinger** [comment]
Sorry for the misunderstanding - RAT checks itself during build:
https://github.com/apache/creadur-rat/blob/master/pom.xml#L246

Certain files are excluded as they are not part of the released artefact:
https://github.com/apache/creadur-rat/blob/master/pom.xml#L326

So we do not need a header in the Travis file.

**Pull request closed without merging**
