### PR TITLE
WIP: RAT-259: Extract CLI class

### PR DESCRIPTION
**Pull request by ottlinger**

### CODE REVIEW

**Comment by Claudenw** [comment]
Is the goal here just to extract the command line configuration away from the core Report class and just have the Report class work with a configuration class that can be created by any interface (Maven, ANT, command-line, etc.)?

**Comment by ottlinger** [comment]
Originally the idea was to have the same functionality available in the CLI module in order to be invoked from other eco systems (such as Bash/Python). When I had a look in the code I realized that a lot of functionality is missing in the CLI module.

Basically the real work did not start yet, so feel free to contribute. Thanks

**Comment by Claudenw** [comment]
If we merge #157 then we could close this merge request and focus on aligning the CLI, Maven, and ANT interfaces to ensure that they support the basic functionality defined in the `ReportConfiguration` class by opening individual tickets about each misalignment and fixing those.

**Comment by Claudenw** [comment]
I think this was done in RAT-321

**Comment by ottlinger** [comment]
I'll close this PR as work performed in RAT-321 changed the way RAT can be configured. A new PR should adress the possibility to specify a list of files to be scanned via RAT's CLI. Sorry for the confusion and the very long time this topic was untouched - closing the PR is the most honest status update.

**Pull request closed without merging**
