### PR TITLE
RAT-315: Fix build with maven 3.9.x

### PR DESCRIPTION
**Pull request by gnodet**

### CODE REVIEW

**Comment by ottlinger** [comment]
@gnodet which JDK/Mvn combination did you use? Running the branch locally yields compilation problems:

```
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   RatCheckMojoTest.testIt1:135->newRatCheckMojo:57->newRatMojo:74->AbstractMojoTestCase.lookupMojo:127->AbstractMojoTestCase.lookupMojo:178->AbstractMojoTestCase.validateContainerStatus:447 » IllegalAccess class org.apache.maven.plugin.testing.AbstractMojoTestCase tried to access private field org.codehaus.plexus.PlexusTestCase.container (org.apache.maven.plugin.testing.AbstractMojoTestCase and org.codehaus.plexus.PlexusTestCase are in unnamed module of loader 'app')
[ERROR]   RatCheckMojoTest.testIt2:147->newRatCheckMojo:57->newRatMojo:74->AbstractMojoTestCase.lookupMojo:127->AbstractMojoTestCase.lookupMojo:178->AbstractMojoTestCase.validateContainerStatus:447 » IllegalAccess class org.apache.maven.plugin.testing.AbstractMojoTestCase tried to access private field org.codehaus.plexus.PlexusTestCase.container (org.apache.maven.plugin.testing.AbstractMojoTestCase and org.codehaus.plexus.PlexusTestCase are in unnamed module of loader 'app')
[ERROR]   RatCheckMojoTest.testIt3:187->newRatMojo:74->AbstractMojoTestCase.lookupMojo:127->AbstractMojoTestCase.lookupMojo:178->AbstractMojoTestCase.validateContainerStatus:447 » IllegalAccess class org.apache.maven.plugin.testing.AbstractMojoTestCase tried to access private field org.codehaus.plexus.PlexusTestCase.container (org.apache.maven.plugin.testing.AbstractMojoTestCase and org.codehaus.plexus.PlexusTestCase are in unnamed module of loader 'app')
[ERROR]   RatCheckMojoTest.testIt4:222->newRatCheckMojo:57->newRatMojo:74->AbstractMojoTestCase.lookupMojo:127->AbstractMojoTestCase.lookupMojo:178->AbstractMojoTestCase.validateContainerStatus:447 » IllegalAccess class org.apache.maven.plugin.testing.AbstractMojoTestCase tried to access private field org.codehaus.plexus.PlexusTestCase.container (org.apache.maven.plugin.testing.AbstractMojoTestCase and org.codehaus.plexus.PlexusTestCase are in unnamed module of loader 'app')
[INFO] 

```

**Comment by nielsbasjes** [comment]
Am I correct this fix should also resolve these Plugin validation issues reported by Maven 3.9.2 ?
```
[WARNING]  * org.apache.rat:apache-rat-plugin:0.15
...
[WARNING]   Plugin issue(s):
[WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
[WARNING]    * Plugin depends on plexus-container-default, which is EOL
[WARNING] 
```

**Comment by gnodet** [comment]
> Am I correct this fix should also resolve these Plugin validation issues reported by Maven 3.9.2 ?
> 
> ```
> [WARNING]  * org.apache.rat:apache-rat-plugin:0.15
> ...
> [WARNING]   Plugin issue(s):
> [WARNING]    * Plugin is a Maven 2.x plugin, which will be not supported in Maven 4.x
> [WARNING]    * Plugin depends on plexus-container-default, which is EOL
> [WARNING] 
> ```

Yes, this PR also removes the warnings caused by the rat plugin with maven 3.9.x.

**Review by slachiewicz — APPROVED** [review]

**Comment by ottlinger** [comment]
@slachiewicz This fix cannot be merged yet as it breaks the older versions of RAT. 
I pressume doing a final 0.x release of RAT before changing the minor JDK versions of dependencies to JDK11 would help here (same as non-functioning upgrade of mockito due to the JDK8 restriction). I did not have time to start the discussion on the mailing list .....

**Comment by kwin** [comment]
@ottlinger I don't think that any of the changes proposed in the PR require either building nor running with JDK11.

**Comment by gnodet** [comment]
> @ottlinger I don't think that any of the changes proposed in the PR require either building nor running with JDK11.

Maven 3.2.5 requires JDK 6, see https://maven.apache.org/docs/history.html

**Comment by ottlinger** [comment]
Sorry to have caused a misunderstaning: as RAT relies on ancient Maven and JDK versions I thought of updating both with a new v1.x. Thus 0.x would remain with Maven2 and JDK8, while v1.x would allow to use more modern libraries and build dependencies.

**Review by Claudenw — APPROVED** [review]
Compiles for me under 
```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /home/claude/bin/apache-maven-3.9.1
Java version: 11.0.19, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.19.0-46-generic", arch: "amd64", family: "unix"
```
and
```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Maven home: /home/claude/bin/apache-maven-3.9.1
Java version: 1.8.0_362, vendor: Private Build, runtime: /usr/lib/jvm/java-8-openjdk-amd64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.19.0-46-generic", arch: "amd64", family: "unix"
```

**Pull request merged**
