### PR TITLE
RAT-343: Enhance documentation about new configuration options

### PR DESCRIPTION
**Pull request by ottlinger**
Fix and enhance documentation about how to configure custom licenses.

### CODE REVIEW

**Comment by ottlinger** [comment]
@Claudenw pls review - I already deployed this branch to:
https://creadur.apache.org/rat0161/apache-rat-plugin/examples/custom-license.html

------

@solomax @garydgregory would this info be helpful for you (if it had been included in r0.16 ;))
Thanks for feedback.

**Comment by garydgregory** [comment]
When I got the error in 0.16.0, the first thing I did was look at the site, whi h was wrong. Then the JIRA was updated with corrected XML, so I used that.

**Comment by solomax** [comment]
@ottlinger Maybe it would be possible to add example for `Matcher details` section? :)

**Comment by solomax** [comment]
And maybe a NOTE regarding custom license name 
Like `If default licences are enabled, please make sure custom license has unique name` :)

**Comment by ottlinger** [comment]
@solomax does the current version contain all your answers or did we miss something? спасибо
https://creadur.apache.org/rat0161/apache-rat-plugin/examples/custom-license.html

**Comment by solomax** [comment]
@ottlinger Thanks for the additional examples! Everything is very clear :)

**Pull request merged**
